---
title: "Physical"
name: "Jarrod Harris"
date: "Summer 2025"
output: html_document
---

```{r include=FALSE,echo=FALSE}
require(knitr)
require(tidyverse)
require(tigerstats)
data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt", sep="", header=TRUE)
```


```{r}
simp <- lm(SIMS ~ ARM, data = data)
plot(SIMS~ARM,data=data)
abline(simp)
summary.lm(simp)
```
```{r}
target<-data.frame(ARM=88, GRIP=94)
```
 
```{r}
predict(simp,target,interval=c("prediction"))
```

```{r}
newGRIP <- lm(SIMS ~ GRIP, data = data)
plot(SIMS~ GRIP,data=data)
abline(newGRIP)
summary.lm(newGRIP)
```

```{r}
predict(newGRIP,target,interval=c("prediction"))
```

```{r}
ARMGRIP_2 <- lm(SIMS~ARM + GRIP, data = data)
plot(SIMS~ARM + GRIP,data=data)
abline(ARMGRIP_2)
summary.lm(ARMGRIP_2)
```

```{r}
predict(ARMGRIP_2,target,interval=c("prediction"))
```

Now what were going to do is compare our three models using the ANOVA command. First were going to compare the model which is halfGRIP with the model simp

```{r}

```

